# environment.yaml - a YAML file describing the minimally specified conda environment 
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually
# install via `conda env create -f conda-env.yaml`
# update (either new or upgraded depedencies) via `conda env update -f conda-env.yaml`
# create a 'locked' version of all dependencies via `conda env export > conda-env.yaml.lock`

name: {{cookiecutter.project_slug}}

channels:
- conda-forge
- defaults

dependencies:
- python={{cookiecutter.python_version}}
- numpy
- pandas
- pip:
    - 
	